tools/elfutils update to 0.191
Release Notes:
https://sourceware.org/pipermail/elfutils-devel/2024q1/006876.html

Manually refresh:
- 100-portability.patch

Change:
- replace libgen.h with gnulib "dirname" module for compilation errors:
    In file included from ./../libdw/libdwP.h:38,
                     from eblobjnote.c:42:
    /usr/include/libgen.h:35:9: error: attempt to use poisoned "basename"
       35 | #define basename        __xpg_basename
          |         ^

- include libeu.h in elf_end.c to fix compilation error:
elf_end.c:135:2: error: call to undeclared function 'tdestroy'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        tdestroy (rawchunks, free_chunk);

- disable inline declaration of reallocarray in system.h to fix build errors:
In file included from xasprintf.c:37:
./system.h:101:1: error: static declaration of 'reallocarray' follows non-static declaration
reallocarray (void *ptr, size_t nmemb, size_t size)

Co-Developed-by: Nick Hainke <vincent@systemli.org>
Signed-off-by: Nick Hainke <vincent@systemli.org>
Signed-off-by: Tony Ambardar <itugrok@yahoo.com>
Signed-off-by: Georgi Valkov <gvalkov@gmail.com>